### ISSUE TITLE
Problems with rails 2.3.9

### ISSUE THREAD

**Issue by jarl-dk** [collectiveidea/migration_test_helper#1]
With rails 2.3.9 there is a problem:

Installing the plugin with ./script/plugin results in
    DEPRECATION WARNING: Rake tasks in vendor/plugins/migration_test_helper/tasks

If I try to install the gem and use it that way the rake task `test:igrations` is missing and my migrations tests is not run as part of rake test

**Comment by kylejusticemagnuson** [comment]
Hi there! We’re doing some open source maintenance work and closing old Issues. If you would still like this Issue to be addressed, please re-open it by 2-weeks-from-today. Thanks!
