### ISSUE TITLE
RDoc deprecation warning with RDoc 2.4.2+

### ISSUE THREAD

**Issue by dmajda** [collectiveidea/migration_test_helper#2]
When running e.g. `rake -T`, the following deprecation warning appears:

```
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
```

**Comment by kylejusticemagnuson** [comment]
Hi there! We’re doing some open source maintenance work and closing old Issues. If you would still like this Issue to be addressed, please re-open it by 2-weeks-from-today. Thanks!
