### ISSUE TITLE
Hoe deprecation warning with Hoe 2.12.2

### ISSUE THREAD

**Issue by dmajda** [collectiveidea/migration_test_helper#4]
When running e.g. `rake -T`, the following deprecation warning appears:

```
Hoe.new {...} deprecated. Switch to Hoe.spec.
```

**Comment by kylejusticemagnuson** [comment]
Hi there! We’re doing some open source maintenance work and closing old Issues. If you would still like this Issue to be addressed, please re-open it by 2-weeks-from-today. Thanks!
