### ISSUE TITLE
Rake Tasks not loading

### ISSUE THREAD

**Issue by HoneyryderChuck** [collectiveidea/migration_test_helper#7]
Greetings,

I am using Rails 3 with Ruby 1.9.3. The gem loads some rake tasks (defined in migration_test_helper_tasks.rake) to (I suppose) run all migration tests at once. Thing is, I cannot call them. Neither test:migration nor test:migrations work. How can this be? 

Looking forward for the reply. 

Cheers,
Tiago

**Comment by kylejusticemagnuson** [comment]
Hi there! We’re doing some open source maintenance work and closing old Issues. If you would still like this Issue to be addressed, please re-open it by 2-weeks-from-today. Thanks!
